[project]
name = "kexploit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "capstone>=5.0.6",
    "deepagents>=0.3.12",
    "keystone-engine>=0.9.2",
    "langchain>=1.2.7",
    "litellm>=1.80.10",
    "multilspy>=0.0.15",
    "mypy>=1.16.1",
    "openai>=1.82.1",
    "pwntools>=4.14.1",
    "pycparser>=2.22",
    "pydantic>=2.11.5",
    "pyelftools>=0.32",
    "pyghidra>=2.1.0",
    "pylspclient>=0.1.2",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "rich>=14.0.0",
    "sqlalchemy>=2.0.45",
    "typer>=0.16.0",
    "kexploit_agent",
    "langchain-openai>=1.1.8",
    "kexploit_utils",
    "langgraph>=1.0.7",
]

[tool.uv]
package = true

[tool.uv.sources]
kexploit_agent = { workspace = true }
kexploit_utils = { workspace = true }

[tool.mypy]
mypy_path = "src"

[project.scripts]
kexploit = "kexploit.main:main"
